version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app  # Mount the code so changes apply without rebuilding the container
    environment:
      - PYTHONUNBUFFERED=1 # So Python logs are printed to the Docker console immediately
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb # The backend starts after the DB

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Isolate the container's node_modules from the host machine
    depends_on:
      - backend
volumes:
  mongo_data: